# -*- coding: utf-8 -*-
"""Copy of TECH16_LLM_Lecture1_prepared.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13539FKSlo1FhUGXaoSOFfRl44yUaoOA6
"""

!pip install openai

from openai import OpenAI
from google.colab import userdata

open_ai_key = userdata.get('open_ai_key')

client = OpenAI(api_key=open_ai_key)

response = client.chat.completions.create(
  model="gpt-3.5-turbo",
  # response_format={ "type": "json_object" },
  messages=[
    {"role": "system", "content": "You are an AI that takes instructions from a human and produces an answer. Be concise in your output."},
    {"role": "user", "content": "Compose a haiku about students studing large language models in Stanford on a Wednesday night."}
  ]
)

print(response)

print(response.choices[0].message.content)

def chat(message):
    """
    Send a message to the OpenAI GPT-3.5 model and return its response.

    This function interacts with the OpenAI API, specifically using the GPT-3.5-turbo model. It takes a user's message as input, sends it to the model, and returns the model's text-only response. The function ensures the AI's output is concise by providing a system-level instruction.

    Parameters:
    message (str): A string containing the user's message to the AI.

    Returns:
    str: The text response generated by the GPT-3.5 model.
    """

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are an AI that takes instructions from a human and produces an answer. Be concise in your output."},
            {"role": "user", "content": f"{message}"}
        ]
    )

    text_only = response.choices[0].message.content
    return text_only

chat("What is the tallest building in NYC?")

"""# Homework starter"""

from openai import OpenAI
from google.colab import userdata

open_ai_key = userdata.get('open_ai_key')

client = OpenAI(api_key=open_ai_key)

response = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "Summarize the text into a headline"},
    {"role": "user", "content": """
	      Meta will reward shareholders with its first-ever dividend and an additional $50bn in share buybacks
        as bumper fourth-quarter results sent its shares up by more than 14 per cent in after-hours trading
        on Thursday.
        """}
  ]
)

summary = response.choices[0].message.content
print(summary)